spring:
  profiles:
    active: dev

rest:
  # 20층
  #url: http://125.141.17.60:60003/cloud/v1
  # AWS
  url: http://api.aws.hamon.vip/cloud/v1

---
server:
  port: 8080
  servlet:
    context-path: /

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/netiscloud?&serverTimezone=Asia/Seoul&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: ntflow
    mapper-locations: classpath:mapper/**/*Mapper.xml

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*

pagehelper:
  helper-dialect: h2
  auto-dialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true
---
server:
  port: 9090
  servlet:
    context-path: /

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    mapper-locations: classpath:mapper/**/*Mapper.xml
    jdbc-url: jdbc:mariadb://database-1.c7guygjgqqpy.ap-northeast-2.rds.amazonaws.com:53306/netiscloud?&serverTimezone=Asia/Seoul&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: portal
    password: vhxkf1234!

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*

pagehelper:
  helper-dialect: h2
  auto-dialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true
