spring:
  profiles:
    active: dev

---
server:
  port: 8080
  servlet:
    context-path: /portal

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  main:
    allow-bean-definition-overriding: true

  datasource:
#    driver: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://localhost:3306/book_ex?&serverTimezone=Asia/Seoul&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/book_ex?&serverTimezone=Asia/Seoul&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: jay
    password: jay.123
    mapper-locations: classpath:mapper/**/*Mapper.xml
#    url: jdbc:h2:tcp://localhost/~/test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*

---
server:
  port: 8080
  servlet:
    context-path: /portal

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    mapper-locations: classpath:mapper/**/*Mapper.xml
    jdbc-url: jdbc:mariadb://localhost:53306/netis?&serverTimezone=Asia/Seoul&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: ntflow

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*

