drop table if exist member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key(id)
);

create table member
(
    id bigint NOT NULL auto_increment,
    name varchar(255),
    primary key(id)
);


-- netiscloud.tblicensepolicy definition

CREATE TABLE `tblicensepolicy` (
  `licensepolicyid` varchar(36) NOT NULL COMMENT '라이센스정책관리번호(uuid)',
  `solutioncode` varchar(6) NOT NULL COMMENT '솔루션코드(groupcode:002)',
  `policycode` varchar(6) NOT NULL COMMENT '라이센스등급(groupcode:001)',
  `solutionname` varchar(50) NOT NULL COMMENT '라이센스정책솔루션명',
  `policyname` varchar(50) NOT NULL COMMENT '라이센스정책명',
  `licensecontent` text NOT NULL COMMENT '라이센스정책내용',
  `licenseamount` varchar(15) NOT NULL COMMENT '라이센스기본요금',
  `licenseint` int(4) NOT NULL COMMENT '라이센스가용장비수',
  `aidcode` varchar(6) NOT NULL COMMENT '지원기능구분(003)',
  `stdate` varchar(8) NOT NULL DEFAULT date_format(curdate(),'%Y%m%d') COMMENT '시작일자',
  `eddate` varchar(8) NOT NULL DEFAULT '21991231' COMMENT '종료일자',
  `useyn` varchar(1) NOT NULL DEFAULT '1' COMMENT '사용여부',
  `sortno` tinyint(1) NOT NULL COMMENT '정렬기준',
  `createdAt` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록일시',
  `updatedAt` datetime NOT NULL DEFAULT current_timestamp() COMMENT '수정일시',
  PRIMARY KEY (`licensepolicyid`),
  KEY `IDX_tbpricepolicy_001` (`policycode`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='라이센스정책관리';

-- tbmember cloudgrade column 변경 -> licensegrade
ALTER TABLE tbmember CHANGE cloudgrade licensegrade VARCHAR(06);
-- tbmember column 추가 -> administratoryn
ALTER TABLE tbmember ADD COLUMN administratoryn VARCHAR(1) AFTER emailcertificationyn;


CREATE TABLE `tbusedevice` (
  `tbusedeviceid` varchar(36) NOT NULL COMMENT '사용자아이디',
  `user_id` varchar(50) NOT NULL COMMENT '사용자아이디',
  `useday` varchar(8) NOT NULL COMMENT '사용일자',
  `tran_status` int(1) NOT NULL COMMENT '처리여부',
  `info` varchar(100) NOT NULL COMMENT '장비정보',
  `nms_count` int(4) NOT NULL COMMENT '네트워크 장비 대수',
  `sms_count` int(4) NOT NULL COMMENT 'sms 장비 대수',
  `dbms_count` int(4) NOT NULL COMMENT 'dbms 장비 대수',
  `ap_count` int(4) NOT NULL COMMENT 'ap 장비 대수',
  `fms_count` int(4) NOT NULL COMMENT 'fms 장비 대수',
  `reason` varchar(8) NOT NULL COMMENT '결과 사용',
  PRIMARY KEY (`tbusedeviceid`),
  KEY `IDX_tbusedevice_001` (`user_id`,`useday`),
  CONSTRAINT `tbusedevice_user_id_FK` FOREIGN KEY (`user_id`) REFERENCES `tbmember` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='사용자등록장비';


<select id="login" resultType="Member">
    select * from tbmember
    where email=#{uid} and password=SHA2(#{upw},256)
</select>

alter table tbmember add column sessionkey varchar(50) not null default 'none';
alter table tbmember add column sessionlimit timestamp;

/* 2023.08.31 추가 */
alter table tbmember add column administratoryn varchar(1) DEFAULT 'N' COMMENT '관리자여부(groupcode=999) 사업자등록번호가 하몬인경우',


implementation group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1.1'